source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Ion_Example', :exclusive => true do
  pod "Ion", :path => "../"
end

target 'Ion_Tests', :exclusive => true do
    pod 'Quick'
    pod 'Nimble'
end
