source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Ion_Example' do
  pod "Ion", :path => "../"

	target 'Ion_Tests' do
		pod 'Quick', '~> 0.10.0'
		pod 'Nimble', '~> 5.0.0'
	end

end
